- hosts: apache
  user: ubuntu
  sudo: yes
  tasks:
    - name: Install apache2 and dependencies
      apt: name={{ item }} state=latest
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip

    - name: Create a directory
      file: path=/var/www/vhosts/versushorse state=directory owner=www-data group=www-data mode=0775

    - name: Populate that directory
      copy: src="../versushorse/" dest="/var/www/vhosts/versushorse/"  owner=www-data group=www-data mode=0664
      notify:
        - restart apache2

    - name: Install prereqs
      pip: requirements=/var/www/vhosts/versushorse/requirements.txt

    - name: Disable the old default site
      file:
        path=/etc/apache2/sites-enabled/000-default.conf
        state=absent
      notify:
        - restart apache2

    - name: Copy config
      copy:
        src="static/versushorse.conf"
        dest="/etc/apache2/sites-available/versushorse.conf"
        owner=root group=root mode=0644

    - name: Enable mod-wsgi
      apache2_module: state=present name=wsgi
      notify:
        - restart apache2

    - name: Enable site
      file:
        src=/etc/apache2/sites-available/versushorse.conf
        dest=/etc/apache2/sites-enabled/100-versushorse.conf
        state=link
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
